- src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/Member.java
- src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/enumType/PlatformEnum.java
- src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/enumType/Role.java
- src/main/java/com/darknights/devigation/member/query/domain/aggregate/entity/QueryMember.java
- src/main/java/com/darknights/devigation/member/query/domain/aggregate/entity/enumType/PlatformEnum.java
- src/main/java/com/darknights/devigation/member/query/domain/aggregate/entity/enumType/Role.java
---
* #3 
---
---
* 없음
---
---
* 맴버 command, query 엔티티를 생성하였습니다.
---
---
* 추후 spring security 적용에 따라 컬럼이 수정될 수 있습니다.
---
---
* 없음
> [Closes #3] Feat : 맴버 command, query 엔티티 생성

- src/main/java/com/darknights/devigation/post/command/domain/aggregate/entity/Post.java
- src/main/java/com/darknights/devigation/post/command/domain/aggregate/vo/MemberVO.java
- src/main/java/com/darknights/devigation/post/query/domain/entity/QueryPost.java
---
* #14 
---
---
* 없음
---
---
* 생성 컬럼
---
---
---
---
* 없음
> [Closes #14] 게시글 Entity 생성

- src/main/java/com/darknights/devigation/category/command/domain/aggregate/entity/Category.java
- src/main/java/com/darknights/devigation/category/command/domain/aggregate/vo/MemberVO.java
- src/main/java/com/darknights/devigation/category/query/domain/aggregate/entity/QueryCategory.java
- src/main/java/com/darknights/devigation/category/query/domain/aggregate/vo/MemberVO.java
---
* #10 
---
---
* 없음
---
---
* category context entity 작성
---
---
* 없음
---
---
* 없음.
> [Closes #10]category context entity 작성

- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/Roadmap.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapCategory.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/ChildCategoryVO.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/MemberVO.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/ParentCategoryVO.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/vo/RoadmapVO.java
- src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/entity/QueryRoadmap.java
- src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/entity/QueryRoadmapCategory.java
- src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/ChildCategoryVO.java
- src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/MemberVO.java
- src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/ParentCategoryVO.java
- src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/vo/RoadmapVO.java
---
* #12 
---
---
* 없음
---
---
* roadmap context command, query entity 작성
---
---
* 없음
---
---
* 없음.
> [Closes #12] roadmap context entity 작성

- src/main/java/com/darknights/devigation/member/command/domain/repository/MemberRepository.java
- src/main/java/com/darknights/devigation/member/query/domain/repository/MemberMapper.java
- src/main/java/com/darknights/devigation/member/query/domain/repository/MemberQueryRepository.java
- src/main/resources/mapper/member/MemberMapper.xml
---
* #4 
* #5 
---
---
* 없음
---
---
* 맴버 mapper, repository 인터페이스 생성
---
---
* 없음
---
---
* 없음
> [#4, #5] Feat : 맴버 mapper, repository 인터페이스 생성

- src/main/java/com/darknights/devigation/category/command/application/dto/CreateCategoryDTO.java
- src/main/java/com/darknights/devigation/category/command/application/dto/UpdateCategoryDTO.java
- src/main/java/com/darknights/devigation/category/command/application/service/CreateCategoryService.java
- src/main/java/com/darknights/devigation/category/command/application/service/DeleteCategoryService.java
- src/main/java/com/darknights/devigation/category/command/application/service/UpdateCategoryService.java
- src/main/java/com/darknights/devigation/category/command/domain/aggregate/entity/Category.java
- src/main/java/com/darknights/devigation/category/command/domain/repository/CategoryRepository.java
- src/main/java/com/darknights/devigation/category/command/domain/service/CategoryService.java
- src/test/java/com/darknights/devigation/category/service/CategoryServiceTests.java
---
* #20 
---
---
* 없음
---
---
* category context create, update delete 기능 작성
* test 코드 작성
---
---
* 기타 참고 사항이 있으면 참조한다.
*
---
---
*
> [Closes #20] Feat : category context Create, Update, Delete 기능 작성, Test : category Context CUD test작성

- src/main/java/com/darknights/devigation/member/command/application/dto/CreateMemberDTO.java
- src/main/java/com/darknights/devigation/member/command/application/service/CreateMemberService.java
- src/main/java/com/darknights/devigation/member/command/domain/aggregate/entity/Member.java
- src/main/resources/mapper/member/MemberMapper.xml
- src/test/java/com/darknights/devigation/member/command/application/service/CreateMemberServiceTest.java
---
* #4 
---
---
* 없음
---
---
* Create Application Service 클래스 생성
---
---
* 없음
---
---
* 사용자 생성 DTO를 통해 생성이 되는지 확인
> [Closes #4] Feat : Create Application Service 클래스 생성

- src/main/java/com/darknights/devigation/photo/command/domain/aggregate/entity/Photo.java
- src/main/java/com/darknights/devigation/photo/command/domain/aggregate/entity/enumtype/PhotoCategory.java
---
* #17
---
---
* 없음
---
---
* 사진 컬럼에 필요하다고 생각하는 컬럼이 있는지
---
---
* 없음
---
---
* 없음
> [Closes #17] 사진 Entity 생성

- src/main/java/com/darknights/devigation/DevigationApplication.java
- src/main/java/com/darknights/devigation/category/command/domain/service/CategoryService.java
- src/main/java/com/darknights/devigation/roadmap/command/application/dto/CreateRoadmapDTO.java
- src/main/java/com/darknights/devigation/roadmap/command/application/dto/UpdateRoadmapDTO.java
- src/main/java/com/darknights/devigation/roadmap/command/application/service/CreateRoadmapService.java
- src/main/java/com/darknights/devigation/roadmap/command/application/service/DeleteRoadmapService.java
- src/main/java/com/darknights/devigation/roadmap/command/application/service/UpdateRoadmapService.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/RoadmapRepository/RoadmapRepository.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/Roadmap.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/aggregate/entity/RoadmapCategory.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/service/RoadmapService.java
- src/main/java/com/darknights/devigation/roadmap/query/domain/aggregate/entity/QueryRoadmapCategory.java
- src/test/java/com/darknights/devigation/roadmap/service/RoadmapServiceTests.java
…t : roadmap Context CUD test작성
---
* #27 
---
---
* 없음
---
---
* roadmap CRUD기능 및 테스트 코드 작성.
---
---
* 없음
---
---
*
> [Closes #27] Feat : roadmap context Create, Update, Delete 기능 작성, Test : roadmap Context CUD test작성

- src/main/java/com/darknights/devigation/DevigationApplication.java
- src/main/java/com/darknights/devigation/common/filter/JwtExceptionFilter.java
- src/main/java/com/darknights/devigation/common/filter/TokenAuthenticationFilter.java
- src/main/java/com/darknights/devigation/common/handler/CustomOAuth2SuccessHandler.java
- src/main/java/com/darknights/devigation/configuration/SecurityConfiguration.java
- src/main/java/com/darknights/devigation/member/command/application/dto/CreateMemberDTO.java
- src/main/java/com/darknights/devigation/member/command/application/service/CreateMemberService.java
- src/main/java/com/darknights/devigation/member/query/application/dto/FindMemberDTO.java
- src/main/java/com/darknights/devigation/member/query/application/service/FindMemberService.java
- src/main/java/com/darknights/devigation/security/command/application/service/CustomTokenService.java
- src/main/java/com/darknights/devigation/security/command/application/service/CustomUserDetailService.java
- src/main/java/com/darknights/devigation/security/command/application/service/RestAuthenticationEntryPoint.java
- src/main/java/com/darknights/devigation/security/token/UserPrincipal.java
- src/test/java/com/darknights/devigation/common/filter/TokenAuthenticationFilterTest.java
- src/test/java/com/darknights/devigation/security/command/application/service/CustomTokenServiceTest.java
---
* #45 
---
---
* 없음
---
---
* Secuity에서 JWT 토큰을 저장하고 처리하는 과정을 단위 테스트를 진행하였습니다.
* 단위 테스트라 표현한 이유는 이번 테스트는 Servlet 단의 Filter 영역과 연결되는 Spring Security 의 Filter에서 JWT 토큰의 복화화와 사용자 정보를 정상적으로 불러올 수 있는지 테스트했기 때문입니다.
* 또한 JWT 토큰의 생성과 복호화 하였을 때 입력값이 정상적으로 저장되었는지만 테스트하였기 때문입니다.
* 추후 통합 테스트는 Controller 클래스와 Response Entity Class 등이 전부 구현되면 테스트할 예정입니다.
* https://jskim1991.medium.com/spring-boot-tdd-with-spring-boot-starter-security-jwt-d29e455c08cb
* https://github.com/jskim1991/tdd-spring-boot-order/blob/200ec87d7590169f9107e292228a1ea668647879/src/main/java/io/jay/tddspringbootorderinsideout/config/SecurityConfiguration.java
---
* `CustomTokenServiceTest`
* `TokenAuthenticationFilterTest`
---
* 없음
---
---
* `TokenAuthenticationFilterTest`
* tokenAuthenticationFilter 에서 다음 필터로 넘어 가는지 테스트하였습니다.
* …
> [#45] Test : JWT 생성 테스트 코드 작성 및 Spring Security SecurityContextHolder 정상 저장 확인 테스트 코드 작성

- build.gradle
- src/main/java/com/darknights/devigation/roadmap/command/application/controller/RoadmapCategoryController.java
- src/main/java/com/darknights/devigation/roadmap/command/application/dto/CreateEdgeDTO.java
- src/main/java/com/darknights/devigation/roadmap/command/application/dto/CreateNodeDTO.java
- src/main/java/com/darknights/devigation/roadmap/command/domain/service/RoadmapCategoryService.java
---
* #71 
* #73 
---
---
* ## 해당 PR을 merge하면 반드시 Road gradle change 해주셔야합니다 
---
---
* 기존의 naive하게 json을 parsing하는 코드에서 json simple 라이브러리를 사용하여 json을 parsing 하였습니다.
json simple 에서 제공하는 두 가지 자료형인 ``` JSONObject```, ```JSONArray```를 통해 좀 더 가독성 좋은 코드를 구성할 수 있었습니다.
* 두 개의 값을 동시에 return하고 싶을 때 ```org.springframework.data.util.Pair```를 사용할 수 있습니다.
> ```return Pair.of(createNodeDTOS, createEdgeDTOS)``` 와 같이 return 한 값을
```info.getFirst(),info.getSecond()```와 같이 꺼내서 사용할 수 있습니다.
---
---
* 없음
---
---
* 없음
> [Closes #71], [Closes #73] Feat : Roadmap Category controller에서 post 요청 처리, json parsing

- src/test/java/com/darknights/devigation/common/advice/SecurityAdviceIntegrationTest.java
---
* 변경 이유를 작성한다.
* 변경 이유를 작성한다.
---
---
* 어떤 오류, 문제점이 발견되었는 지 작성한다.
*
---
---
* 주요 변경사항, 핵심 변경내용을 작성한다.
*
---
---
* 기타 참고 사항이 있으면 참조한다.
*
---
---
* 테스트 관련 사항을 입력한다.
> [Closes #68, Closes #69] Feat : AccessDeniedException 테스트 코드 완료

- .gitignore
- src/main/java/com/darknights/devigation/common/exception/InvalidParameterException.java
- src/main/java/com/darknights/devigation/common/exception/assertion/ExceptionAssert.java
- src/main/java/com/darknights/devigation/member/query/application/service/FindMemberService.java
- src/test/java/com/darknights/devigation/common/advice/AuthControllerAdviceIntegrationTest.java
---
* #58
---
---
* `application-aws.yml` 파일을 `.gitignore` 에 추가하였습니다.
---
---
* 런타임에서 발생하는 주요 에러들을 체크하는 `ExceptionAssert` 클래스를 생성하였습니다.
* 해당 클래스에서 `null` 값 처리 나 `parameter`의 유효성에 대한 에러를 한번에 정의한 후 해당 static 메소드를 검증이 필요한 영역에서 호출하여 사용하면 됩니다.
**예시**
``` java
// ExceptionAssert.java
public static void isUserExist(Object object) {
if(object == null) {
throw new UserNotFoundException("사용자가 존재하지 않습니다.");
}
}
// FindMemberService.java
public FindMemberDTO findById(long memberId) {
QueryMember findMember = memberMapper.findById(memberId);
ExceptionAssert.isUserExist(findMember);
...
}
```
---
---
* 관련 내용은 추후 Wiki 탭에 정리할 예정입니다.
---
---
* 테스트 관련 사항을 입력한다.
> [Closes #58] Refactor : ExceptionAssert 클래스 생성 및 리펙토링 완료

- src/main/java/com/darknights/devigation/post/command/domain/aggregate/entity/Post.java
---
* Content 최대값 수정
---
---
* 없음
---
---
* 없음
---
> [closes #82] Content 최대값 수정

- src/test/java/com/darknights/devigation/aws/command/application/service/AwsS3ServiceTests.java
---
* aws 발급 키 이슈로 인한 aws 테스트 코드 주석 처리
---
---
* 없음
---
---
* 없음
---
> [closes #88] Aws S3 이미지 테스크 코드 주석처리

- src/test/java/com/darknights/devigation/infra/aws/command/application/service/AwsS3ServiceTests.java
---
* git action 동작 확인을 위해서
---
---
* S3 액세스키 이슈에 따른 테스트 코드 주석처리를 했으나 git action에 테스트가 동작하여 pr들이 git action을 통과하지 못하는 현상 발견
---
---
* 없
---
---
---
---
* 없음
> [closes #94] Git action 오류 해결 테스트

- src/main/java/com/darknights/devigation/domain/category/command/application/dto/CreateCategoryDTO.java
- src/main/java/com/darknights/devigation/domain/category/command/application/dto/UpdateCategoryDTO.java
- src/main/java/com/darknights/devigation/domain/category/command/application/service/UpdateCategoryService.java
- src/main/java/com/darknights/devigation/domain/category/command/domain/aggregate/entity/Category.java
- src/main/java/com/darknights/devigation/domain/category/command/domain/aggregate/entity/enumtype/Classification.java
- src/main/java/com/darknights/devigation/domain/category/command/domain/service/CategoryService.java
- src/test/java/com/darknights/devigation/domain/category/service/CategoryServiceTests.java
---
* #62 
---
---
* 없음
---
---
* 대분류 컬럼을 추가하고 관련 테스트를 진행했습니다.
---
---
* 없음
---
---
* ![image](https://github.com/The-Dark-Nights/back-end/assets/74136791/d6882ba6-91ac-4a1f-9dc1-9e4251b6b7c4)
> [Closes #62] Feat : Category 대분류 column 추가,Test : Category 대분류 column insert, update test

- build.gradle
- src/main/java/com/darknights/devigation/domain/post/command/application/dto/CreatePostDTO.java
- src/main/java/com/darknights/devigation/domain/post/query/application/dto/FindPostDTO.java
- src/main/java/com/darknights/devigation/domain/post/query/application/service/FindPostService.java
- src/main/java/com/darknights/devigation/domain/post/query/domain/repository/PostMapper.java
- src/main/java/com/darknights/devigation/infra/aws/command/application/service/AwsS3Service.java
- src/main/resources/mapper/post/PostMapper.xml
- src/test/java/com/darknights/devigation/domain/post/query/service/PostReadTests.java
---
* #90 
---
---
* 없음
---
---
* 없음
---
---
* 없음
---
---
* 현재 테스트가 불가능한 상황이기 때문에 추후 키 발급 이후 테스트 진행 예정
> [Closes #90] 이미지 용량 제한 설정

- build.gradle
- src/main/java/com/darknights/devigation/domain/post/command/application/controller/PostController.java
- src/main/java/com/darknights/devigation/domain/post/command/application/dto/CreatePostDTO.java
- src/main/java/com/darknights/devigation/domain/post/command/application/dto/ExceptionDTO.java
- src/main/java/com/darknights/devigation/domain/post/command/application/dto/ResponsePostDTO.java
- src/main/java/com/darknights/devigation/domain/post/command/application/dto/UpdatePostDTO.java
- src/main/java/com/darknights/devigation/domain/post/command/application/service/CreatePostService.java
- src/main/java/com/darknights/devigation/domain/post/command/domain/aggregate/entity/Post.java
- src/main/java/com/darknights/devigation/global/advice/AuthControllerAdvice.java
- src/main/java/com/darknights/devigation/global/common/response/api/CustomApiResponse.java
- src/main/java/com/darknights/devigation/global/common/response/error/ErrorResponse.java
- src/main/java/com/darknights/devigation/global/configuration/SecurityConfiguration.java
- src/main/java/com/darknights/devigation/global/configuration/SwaggerConfig.java
- src/main/java/com/darknights/devigation/global/handler/post/PostControllerHandler.java
- src/main/java/com/darknights/devigation/global/security/command/application/controller/AuthController.java
- src/main/java/com/darknights/devigation/global/security/command/application/dto/AuthResponse.java
- src/test/java/com/darknights/devigation/domain/post/command/service/PostCRUDTests.java
- src/test/java/com/darknights/devigation/domain/post/query/service/PostReadTests.java
---
* #92 
---
---
* 없음
---
---
* swagger 적용 및  예외처리
* @RequestBody 를 DTO타입으로 받게 되면 내부적으로 기본생성자를 만들기 때문에 DTO class에 기본생성자를 만들어 줘야합니다.
---
---
---
---
*추후 업로드 예정
> [#92] Post 도메인 controller 작성 및 swagger 적용

- build.gradle
- src/main/java/com/darknights/devigation/domain/member/query/application/controller/FindMemberController.java
---
* #102 
---
---
* 없음
---
---
* 사용자 정보를 조회하는 Controller API를 구현하였습니다.
---
---
* 기타 참고 사항이 있으면 참조한다.
*
---
---
* 테스트 관련 사항을 입력한다.
> [Closes #102] Feat : 사용자 정보 조회 API 구현

- src/main/java/com/darknights/devigation/domain/post/command/application/controller/PostController.java
- src/main/java/com/darknights/devigation/domain/post/command/application/service/CreatePostService.java
- src/test/java/com/darknights/devigation/domain/post/command/service/PostCRUDTests.java
- src/test/java/com/darknights/devigation/domain/post/query/service/PostReadTests.java
---
* #105 
---
---
* 없음
---
---
* CurrentMember 어노테이션을 사용한 token 정보 받기
---
---
* 없음
---
> [closes #105] token으로 사용자 정보확인

- src/main/java/com/darknights/devigation/domain/member/command/domain/aggregate/entity/Member.java
- src/main/java/com/darknights/devigation/domain/member/query/domain/aggregate/entity/QueryMember.java
- src/main/java/com/darknights/devigation/domain/post/command/application/controller/PostController.java
- src/main/java/com/darknights/devigation/global/configuration/SecurityConfiguration.java
- src/main/java/com/darknights/devigation/global/configuration/WebMvcConfiguration.java
- src/main/java/com/darknights/devigation/global/security/command/application/service/CustomOAuth2UserService.java
---
* #107 
---
---
* 없음
---
---
* GitHub 사용자 email과 profileImage를 설정하지 않을 시 null값으로 전달되기 때문에 nullable=false로 해놓은 컬럼에서 오류가 발생한다. 
---
---
* 없음
---
---
* 없음
> [closes #107] Github OAuth로그인시 null값으로 인한 오류 수정

- src/main/java/com/darknights/devigation/domain/member/command/domain/aggregate/entity/Member.java
- src/main/java/com/darknights/devigation/domain/member/query/domain/aggregate/entity/QueryMember.java
- src/main/java/com/darknights/devigation/domain/post/command/application/controller/PostController.java
- src/main/java/com/darknights/devigation/domain/post/query/application/controller/FindPostController.java
- src/main/java/com/darknights/devigation/global/configuration/SecurityConfiguration.java
- src/main/java/com/darknights/devigation/global/configuration/WebMvcConfiguration.java
- src/main/java/com/darknights/devigation/global/security/command/application/service/CustomOAuth2UserService.java
---
* #109 
---
---
* 없음
---
---
* 없음
---
> [closes #109] 글 조회 기능 Controller 작성
